Use of rancher test framework to create initial test set for e2e
SUSE-Enceladus/csp-adapter-rancher-e2e-automation pull request #2
Opened 2023-06-05 21:08 UTC by mbelur

This change supports using the rancher test framework to write tests for the billing adapter.

As example, created two test cases that validates
that both csp-rancher-usage-operator and csp-billing-adapter is running in the cluster.

2023-06-05 21:21 UTC, rtamalin commented on tests/billing_test_utils.go
> +func gettotalCurrentManagedNodes(client *rancher.Client) (totalCurrentManagedNodes int, err error) {
should the `total` here be `Total` to match the camel casing in the rest of the function name?

2023-06-05 21:22 UTC, mbelur commented on tests/billing_test_utils.go
> +func gettotalCurrentManagedNodes(client *rancher.Client) (totalCurrentManagedNodes int, err error) {
I can change that to be consistent

2023-06-06 12:21 UTC, rjschwei requested changes

2023-06-06 12:21 UTC, rjschwei commented on README.md
> +These tests makes use of the rancher test [framework](https://github.com/rancher/rancher/tree/release/v2.7/tests/framework)
s/makes/make/

2023-06-07 17:39 UTC, igomez06 reviewed
Looks great, just had some questions on the client used for getting the nodes, also a nit pick on how to use assert vs require.

2023-06-07 17:39 UTC, igomez06 commented on tests/billing_test_utils.go
> +		Resource: "nodes",
You don't need to redefine the GroupVersionResource multiple times. Also any particular reason you are using the v3 endpoint to get the nodes instead of the v1? Also why not use the Management client instead?

2023-06-07 17:39 UTC, igomez06 commented on tests/billing_payg_test.go
> +	assert.NoError(t.T(), err, "Unable to create the client")
should do require.NoError instead, that way if the client fails to be created it will stop the test.

2023-06-07 17:39 UTC, igomez06 commented on tests/billing_payg_test.go
> +	assert.NoError(t.T(), err, "Unable to create the client")
same here.

2023-06-07 18:21 UTC, mbelur commented on tests/billing_test_utils.go
> +		Resource: "nodes",
Sure will update to define GVR only once. Also regading v3, when I do a

>  kubectl api-resources --api-group=management.cattle.io

It shows only the v3 version for the nodes.

> nodes  management.cattle.io/v3   true Node

Not sure if I'm missing something here..

Could you provide me a reference in the code base to the management client?

2023-06-07 18:21 UTC, mbelur commented on tests/billing_payg_test.go
> +	assert.NoError(t.T(), err, "Unable to create the client")
sure will update it to use require

2023-06-07 18:21 UTC, mbelur commented on tests/billing_payg_test.go
> +	assert.NoError(t.T(), err, "Unable to create the client")
sure will update it to use require

2023-06-07 19:28 UTC, igomez06 commented on tests/billing_test_utils.go
> +		Resource: "nodes",
So management.cattle.io would be the v3 calls, but there is also a v1 call for nodes. Here's an example: 
```
	proxyClient, err := client.Steve.ProxyDownstream(clusterIDName)
 	require.NoError(t, err)
 	assert.NotEmpty(t, proxyClient)
 	nodesList, err := proxyClient.SteveType("node").List(nil)
```

just pointing it out.
The management client would work something like this for nodes

`client.Managment.Node.List()`
here's an example of using the management client for listing projects: https://github.com/rancher/rancher/blob/5b9667d60627cfced1faf7319434f0537a052d15/tests/framework/extensions/projects/projects.go#L41

2023-06-07 21:40 UTC, mbelur commented on tests/billing_test_utils.go
> +		Resource: "nodes",
Thanks for the reference. I have updated the code.

2023-06-07 21:40 UTC, mbelur commented on tests/billing_payg_test.go
> +	assert.NoError(t.T(), err, "Unable to create the client")
Done

2023-06-07 21:40 UTC, mbelur commented on tests/billing_payg_test.go
> +	assert.NoError(t.T(), err, "Unable to create the client")
Done

2023-06-07 23:12 UTC, igomez06 approved these changes
This looks good to me

2023-06-08 13:20 UTC, rjschwei approved these changes

2023-06-08 13:53 UTC, merged